const stages = (...values) => values;

export const CONTROLS = Object.freeze([
  { id: "CTRL-A-01", domain: "A", title: "Purpose and use boundary", requirementIds: ["REQ-A-001"], lifecycleStages: stages("QUALIFICATION_AND_REGISTRATION", "DESIGN_AND_DEVELOPMENT", "REVIEW_AND_EVALUATION"), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["purpose", "prohibited-use", "owner"] },
  { id: "CTRL-A-02", domain: "A", title: "Role and AI classification record", requirementIds: ["REQ-A-002"], lifecycleStages: stages("QUALIFICATION_AND_REGISTRATION", "VERIFICATION_AND_VALIDATION", "REVIEW_AND_EVALUATION"), targetState: "HUMAN_VALIDATED", severity: "CRITICAL", signals: ["classification", "provider-role", "deployer-role"] },
  { id: "CTRL-A-03", domain: "A", title: "Value hypothesis and success measures", requirementIds: ["REQ-A-003"], lifecycleStages: stages("QUALIFICATION_AND_REGISTRATION", "DESIGN_AND_DEVELOPMENT", "REVIEW_AND_EVALUATION"), targetState: "TESTED", severity: "MEDIUM", signals: ["value", "success-metric", "prototype-result"] },
  { id: "CTRL-B-01", domain: "B", title: "Versioned data inventory and flow", requirementIds: ["REQ-B-001"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING"), targetState: "TESTED", severity: "HIGH", signals: ["data-inventory", "data-flow", "retention"] },
  { id: "CTRL-B-02", domain: "B", title: "Privacy basis and DPIA screen", requirementIds: ["REQ-B-002"], lifecycleStages: stages("QUALIFICATION_AND_REGISTRATION", "DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING"), targetState: "HUMAN_VALIDATED", severity: "CRITICAL", signals: ["privacy-review", "lawful-basis", "dpia"] },
  { id: "CTRL-B-03", domain: "B", title: "Confidentiality, IP and licence review", requirementIds: ["REQ-B-003"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT"), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["ip-review", "licence", "confidentiality"] },
  { id: "CTRL-C-01", domain: "C", title: "AI component and dependency inventory", requirementIds: ["REQ-C-001"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING", "REVIEW_AND_EVALUATION"), targetState: "TESTED", severity: "HIGH", signals: ["model-inventory", "provider", "dependency"] },
  { id: "CTRL-C-02", domain: "C", title: "Provider and supply-chain review", requirementIds: ["REQ-C-002"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "REVIEW_AND_EVALUATION"), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["provider-review", "terms", "subprocessor"] },
  { id: "CTRL-C-03", domain: "C", title: "Agent permission and autonomy boundary", requirementIds: ["REQ-C-003"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING"), targetState: "TESTED", severity: "CRITICAL", signals: ["tool-allowlist", "human-approval", "rate-limit", "kill-switch"] },
  { id: "CTRL-D-01", domain: "D", title: "AI security threat model", requirementIds: ["REQ-D-001"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "REVIEW_AND_EVALUATION"), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["threat-model", "prompt-injection", "data-leakage"] },
  { id: "CTRL-D-02", domain: "D", title: "Safety, robustness and performance evaluation", requirementIds: ["REQ-D-002"], lifecycleStages: stages("VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING", "REVIEW_AND_EVALUATION"), targetState: "TESTED", severity: "CRITICAL", signals: ["evaluation", "acceptance-threshold", "red-team"] },
  { id: "CTRL-D-03", domain: "D", title: "Logging, rollback and fail-safe controls", requirementIds: ["REQ-D-003"], lifecycleStages: stages("VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING", "RETIREMENT"), targetState: "TESTED", severity: "HIGH", signals: ["audit-log", "rollback", "safe-shutdown"] },
  { id: "CTRL-E-01", domain: "E", title: "Human-impact and fairness evaluation", requirementIds: ["REQ-E-001"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "REVIEW_AND_EVALUATION"), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["impact-assessment", "fairness", "accessibility"] },
  { id: "CTRL-E-02", domain: "E", title: "Transparency and explanation design", requirementIds: ["REQ-E-002"], lifecycleStages: stages("VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING"), targetState: "TESTED", severity: "HIGH", signals: ["ai-notice", "explanation", "synthetic-content"] },
  { id: "CTRL-E-03", domain: "E", title: "Meaningful oversight and contestability", requirementIds: ["REQ-E-003"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING"), targetState: "TESTED", severity: "CRITICAL", signals: ["human-override", "appeal", "escalation"] },
  { id: "CTRL-F-01", domain: "F", title: "Accountability and decision rights", requirementIds: ["REQ-F-001"], lifecycleStages: stages(...["QUALIFICATION_AND_REGISTRATION", "DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING", "REVIEW_AND_EVALUATION", "RETIREMENT"]), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["accountable-owner", "raci", "decision-rights"] },
  { id: "CTRL-F-02", domain: "F", title: "Risk, control and evidence register", requirementIds: ["REQ-F-002"], lifecycleStages: stages("DESIGN_AND_DEVELOPMENT", "VERIFICATION_AND_VALIDATION", "DEPLOYMENT", "OPERATION_AND_MONITORING", "REVIEW_AND_EVALUATION"), targetState: "HUMAN_VALIDATED", severity: "HIGH", signals: ["risk-register", "residual-risk", "evidence-register"] },
  { id: "CTRL-F-03", domain: "F", title: "Monitoring, change, incident and retirement plan", requirementIds: ["REQ-F-003"], lifecycleStages: stages("DEPLOYMENT", "OPERATION_AND_MONITORING", "REVIEW_AND_EVALUATION", "RETIREMENT"), targetState: "TESTED", severity: "HIGH", signals: ["monitoring-plan", "incident-response", "change-trigger", "retirement-plan"] }
]);

